### ISSUE TITLE
Trained weights

### ISSUE THREAD

**Issue by JSOlier** [wagner-niklas/CAGE_expression_inference#1]
Hi, 
I am trying to use these models for valence estimation. 
However, I am unable to find the trained weights.
Many scripts are loading the file best_model_affectnet_improved7VA, which is not part of the repository.
Where can I find that file?
Thank.

**Comment by wagner-niklas** [comment]
Hi Juan,
thanks for the interest in our project. We will update our files this afternoon.
Best regards,
Niklas

**Comment by FelixMaetzler** [comment]
Hi @JSOlier,
i committed all the scripts we used for our final paper. You can find them in the [models](https://github.com/wagner-niklas/CAGE_expression_inference/tree/main/models) directory. In every subdirectory there is a `train.py` and a `generate_csv.py` file. The first one generates the `model.pt` (it's too large to commit to github) and the second uses this `model.pt` and creates the `inference.csv`.
The [evaluation.py](https://github.com/wagner-niklas/CAGE_expression_inference/blob/main/models/evaluation.py) then uses (or creates) the `inference.csv` and prints the results.

As described in the paper, the `VA` models where trained on top of the `combined` models.

I hope this helps you.
Please feel free to contact us again if you have further questions.

Best regards,
Felix

**Comment by ZayneHuang** [comment]
Hi @FelixMaetzler,

Thanks for your contribution. Could you share the checkpoint files on other platforms like Google Drive?

Or, if I want to train the model on AffectNet, I wonder which model achieved the best accuracy? According to the paper, MaxViT valence−arousal won the best performance in relation to valence and arousal prediction, which is [this model](https://github.com/wagner-niklas/CAGE_expression_inference/tree/main/models/AffectNet8_Maxvit_VA) in the respository. Am I right?

**Comment by wagner-niklas** [comment]
Hi @ZayneHuang,

your right, AffectNet8_Maxvit_VA is our overall best model regarding valence and arousal estimation. Please keep in mind that we initialized the model weights of AffectNet8_Maxvit_Combined in this Script. Therefore, you have to train this model too.

Best regards,
Niklas

**Comment by ZayneHuang** [comment]
> Hi @ZayneHuang,
> 
> your right, AffectNet8_Maxvit_VA is our overall best model regarding valence and arousal estimation. Please keep in mind that we initialized the model weights of AffectNet8_Maxvit_Combined in this Script. Therefore, you have to train this model too.
> 
> Best regards, Niklas

Thanks for your reply and advice : )

**Comment by Varun-GP** [comment]
Thanks for your contribution. Could you please share the checkpoint files maybe on a Google Drive Link? It would greatly help in understanding the model prediction from live videos.
