### ISSUE TITLE
Data Preprocessing

### ISSUE THREAD

**Issue by ZayneHuang** [wagner-niklas/CAGE_expression_inference#3]
Hi @wagner-niklas,

I am trying to train the models to reproduce the results. I found that the key of images in AffectNet dataset is organized in numbers (as shown in `*_set_annotation_without_lnd.csv`). I wonder the way to map the original images to the image numbers. 
Would you please provide codes on data preprocessing for image data, including renaming and processing? Thanks!

Best regards

**Comment by wagner-niklas** [comment]
Hi @ZayneHuang,

The mapping is done via the getitem Method in the Dataset class. As you can see there, the naming of the image files in our AffectNet-dataset where equal to the 'number' column in the csv. As example, we loaded an image via a path similar to "AffectNet8/train/13.png" where "13" equals the number in the .csv . We didn't rename the image files.

Best regards,
Niklas

**Comment by ZayneHuang** [comment]
> Hi @ZayneHuang,
> 
> The mapping is done via the getitem Method in the Dataset class. As you can see there, the naming of the image files in our AffectNet-dataset are equal to the 'number' column in the csv. As example, we loaded an image via a path similar to "AffectNet8/train/13.jpg" where "13" equals the number in the .csv . We didn't rename the image files.
> 
> Best regards, Niklas

Thanks for your response.

It seems that the image files in the AffectNet are not named with numbers but rather with a hash-like filename. The "subDirectory" column in the file_lists CSV file provides numeric values, but they don't correspond to the CSV you provided. 

I would like to further understand the naming convention used for the image files in AffectNet. Or are the files you received from the authors of AffectNet originally named in numbers? Thanks again!

**Comment by wagner-niklas** [comment]
Hi @ZayneHuang,

we got the AffectNet files named as I mentioned and therefore your issue is unfortunately out of our research. Based on your description, you may have to contact the authors of AffectNet: http://mohammadmahoor.com/affectnet/ .

Best regards,
Niklas
